# TCL File Generated by Component Editor 11.1sp2
# Sat Jul 21 18:59:28 CST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | basic_ShieldCtrl "Shield Slot Administrative Controller" v1.0
# | Shyu Lee 2012.07.21.18:59:28
# | 
# | 
# | D:/Lophilo/grid/qsys_root/basic_ShieldCtrl.v
# | 
# |    ./basic_ShieldCtrl.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module basic_ShieldCtrl
# | 
set_module_property NAME basic_ShieldCtrl
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Lophilo/Basic
set_module_property AUTHOR "Shyu Lee"
set_module_property DISPLAY_NAME "Shield Slot Administrative Controller"
set_module_property TOP_LEVEL_HDL_FILE basic_ShieldCtrl.v
set_module_property TOP_LEVEL_HDL_MODULE basic_ShieldCtrl
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME basic_ShieldCtrl
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file basic_ShieldCtrl.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point MRST
# | 
add_interface MRST reset end
set_interface_property MRST associatedClock MCLK
set_interface_property MRST synchronousEdges DEASSERT

set_interface_property MRST ENABLED true

add_interface_port MRST rsi_MRST_reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point MCLK
# | 
add_interface MCLK clock end
set_interface_property MCLK clockRate 0

set_interface_property MCLK ENABLED true

add_interface_port MCLK csi_MCLK_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point Ctrl
# | 
add_interface Ctrl avalon end
set_interface_property Ctrl addressUnits WORDS
set_interface_property Ctrl associatedClock MCLK
set_interface_property Ctrl associatedReset MRST
set_interface_property Ctrl bitsPerSymbol 8
set_interface_property Ctrl burstOnBurstBoundariesOnly false
set_interface_property Ctrl burstcountUnits WORDS
set_interface_property Ctrl explicitAddressSpan 0
set_interface_property Ctrl holdTime 0
set_interface_property Ctrl linewrapBursts false
set_interface_property Ctrl maximumPendingReadTransactions 0
set_interface_property Ctrl readLatency 0
set_interface_property Ctrl readWaitTime 1
set_interface_property Ctrl setupTime 0
set_interface_property Ctrl timingUnits Cycles
set_interface_property Ctrl writeWaitTime 0

set_interface_property Ctrl ENABLED true

add_interface_port Ctrl avs_Ctrl_writedata writedata Input 32
add_interface_port Ctrl avs_Ctrl_readdata readdata Output 32
add_interface_port Ctrl avs_Ctrl_byteenable byteenable Input 4
add_interface_port Ctrl avs_Ctrl_write write Input 1
add_interface_port Ctrl avs_Ctrl_read read Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point OC
# | 
add_interface OC interrupt end
set_interface_property OC associatedAddressablePoint Ctrl
set_interface_property OC associatedClock MCLK

set_interface_property OC ENABLED true

add_interface_port OC ins_OC_irq irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point EXPORT
# | 
add_interface EXPORT conduit end

set_interface_property EXPORT ENABLED true

add_interface_port EXPORT coe_A_OCN export Input 1
add_interface_port EXPORT coe_A_PWREN export Output 1
add_interface_port EXPORT coe_A_HOE export Output 1
add_interface_port EXPORT coe_A_LOE export Output 1
add_interface_port EXPORT coe_B_OCN export Input 1
add_interface_port EXPORT coe_B_PWREN export Output 1
add_interface_port EXPORT coe_B_HOE export Output 1
add_interface_port EXPORT coe_B_LOE export Output 1
# | 
# +-----------------------------------
