# TCL File Generated by Component Editor 11.1sp2
# Sat Jul 21 18:57:28 CST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | basic_FuncLED "Function RGB LED Controller" v1.0
# | Shyu Lee 2012.07.21.18:57:28
# | 
# | 
# | D:/Lophilo/grid/qsys_root/basic_FuncLED.v
# | 
# |    ./basic_FuncLED.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module basic_FuncLED
# | 
set_module_property NAME basic_FuncLED
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Lophilo/Basic
set_module_property AUTHOR "Shyu Lee"
set_module_property DISPLAY_NAME "Function RGB LED Controller"
set_module_property TOP_LEVEL_HDL_FILE basic_FuncLED.v
set_module_property TOP_LEVEL_HDL_MODULE basic_FuncLED
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME basic_FuncLED
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file basic_FuncLED.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point MRST
# | 
add_interface MRST reset end
set_interface_property MRST associatedClock MCLK
set_interface_property MRST synchronousEdges DEASSERT

set_interface_property MRST ENABLED true

add_interface_port MRST rsi_MRST_reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point MCLK
# | 
add_interface MCLK clock end
set_interface_property MCLK clockRate 0

set_interface_property MCLK ENABLED true

add_interface_port MCLK csi_MCLK_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point LEDD
# | 
add_interface LEDD avalon end
set_interface_property LEDD addressUnits WORDS
set_interface_property LEDD associatedClock MCLK
set_interface_property LEDD associatedReset MRST
set_interface_property LEDD bitsPerSymbol 8
set_interface_property LEDD burstOnBurstBoundariesOnly false
set_interface_property LEDD burstcountUnits WORDS
set_interface_property LEDD explicitAddressSpan 0
set_interface_property LEDD holdTime 0
set_interface_property LEDD linewrapBursts false
set_interface_property LEDD maximumPendingReadTransactions 0
set_interface_property LEDD readLatency 0
set_interface_property LEDD readWaitTime 1
set_interface_property LEDD setupTime 0
set_interface_property LEDD timingUnits Cycles
set_interface_property LEDD writeWaitTime 0

set_interface_property LEDD ENABLED true

add_interface_port LEDD avs_LEDD_writedata writedata Input 32
add_interface_port LEDD avs_LEDD_readdata readdata Output 32
add_interface_port LEDD avs_LEDD_byteenable byteenable Input 4
add_interface_port LEDD avs_LEDD_write write Input 1
add_interface_port LEDD avs_LEDD_read read Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point LEDS
# | 
add_interface LEDS avalon_streaming end
set_interface_property LEDS associatedClock MCLK
set_interface_property LEDS associatedReset MRST
set_interface_property LEDS dataBitsPerSymbol 8
set_interface_property LEDS errorDescriptor ""
set_interface_property LEDS firstSymbolInHighOrderBits true
set_interface_property LEDS maxChannel 0
set_interface_property LEDS readyLatency 0

set_interface_property LEDS ENABLED true

add_interface_port LEDS asi_LEDS_data data Input 24
add_interface_port LEDS asi_LEDS_valid valid Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point EXPORT
# | 
add_interface EXPORT conduit end

set_interface_property EXPORT ENABLED true

add_interface_port EXPORT coe_LED_R export Output 1
add_interface_port EXPORT coe_LED_G export Output 1
add_interface_port EXPORT coe_LED_B export Output 1
# | 
# +-----------------------------------
