# TCL File Generated by Component Editor 11.1sp2
# Fri Jul 20 15:16:31 CST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | qsys_shield_gpioFuncSel "GPIO Function Controller" v1.0
# | Shyu Lee 2012.07.20.15:16:31
# | 
# | 
# | D:/Lophilo/grid/qsys_root/qsys_shield_gpioFuncSel.v
# | 
# |    ./qsys_shield_gpioFuncSel.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module qsys_shield_gpioFuncSel
# | 
set_module_property NAME qsys_shield_gpioFuncSel
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Lophilo/Shield
set_module_property AUTHOR "Shyu Lee"
set_module_property DISPLAY_NAME "GPIO Function Controller"
set_module_property TOP_LEVEL_HDL_FILE qsys_shield_gpioFuncSel.v
set_module_property TOP_LEVEL_HDL_MODULE qsys_shield_gpioFuncSel
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME qsys_shield_gpioFuncSel
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file qsys_shield_gpioFuncSel.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point MRST
# | 
add_interface MRST reset end
set_interface_property MRST associatedClock MCLK
set_interface_property MRST synchronousEdges DEASSERT

set_interface_property MRST ENABLED true

add_interface_port MRST rsi_MRST_reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point MCLK
# | 
add_interface MCLK clock end
set_interface_property MCLK clockRate 0

set_interface_property MCLK ENABLED true

add_interface_port MCLK csi_MCLK_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point ctrl
# | 
add_interface ctrl avalon end
set_interface_property ctrl addressUnits WORDS
set_interface_property ctrl associatedClock MCLK
set_interface_property ctrl associatedReset MRST
set_interface_property ctrl bitsPerSymbol 8
set_interface_property ctrl burstOnBurstBoundariesOnly false
set_interface_property ctrl burstcountUnits WORDS
set_interface_property ctrl explicitAddressSpan 0
set_interface_property ctrl holdTime 0
set_interface_property ctrl linewrapBursts false
set_interface_property ctrl maximumPendingReadTransactions 0
set_interface_property ctrl readLatency 0
set_interface_property ctrl readWaitTime 1
set_interface_property ctrl setupTime 0
set_interface_property ctrl timingUnits Cycles
set_interface_property ctrl writeWaitTime 0

set_interface_property ctrl ENABLED true

add_interface_port ctrl avs_ctrl_writedata writedata Input 8
add_interface_port ctrl avs_ctrl_readdata readdata Output 8
add_interface_port ctrl avs_ctrl_write write Input 1
add_interface_port ctrl avs_ctrl_read read Input 1
add_interface_port ctrl avs_ctrl_waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point EXPORT
# | 
add_interface EXPORT conduit end

set_interface_property EXPORT ENABLED true

add_interface_port EXPORT coe_f0_oe export Input 1
add_interface_port EXPORT coe_f1_oe export Input 1
add_interface_port EXPORT coe_f2_oe export Input 1
add_interface_port EXPORT coe_f3_oe export Input 1
add_interface_port EXPORT coe_f4_oe export Input 1
add_interface_port EXPORT coe_f5_oe export Input 1
add_interface_port EXPORT coe_f6_oe export Input 1
add_interface_port EXPORT coe_f7_oe export Input 1
add_interface_port EXPORT coe_f0_out export Input 1
add_interface_port EXPORT coe_f1_out export Input 1
add_interface_port EXPORT coe_f2_out export Input 1
add_interface_port EXPORT coe_f3_out export Input 1
add_interface_port EXPORT coe_f4_out export Input 1
add_interface_port EXPORT coe_f5_out export Input 1
add_interface_port EXPORT coe_f6_out export Input 1
add_interface_port EXPORT coe_f7_out export Input 1
add_interface_port EXPORT coe_f_in export Output 1
add_interface_port EXPORT coe_GPIO export Bidir 1
# | 
# +-----------------------------------
