# TCL File Generated by Component Editor 11.1sp2
# Sat Jul 21 19:01:59 CST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | test_LEDState "LED State Generator" v1.0
# | Shyu Lee 2012.07.21.19:01:59
# | 
# | 
# | D:/Lophilo/grid/qsys_root/test_LEDState.v
# | 
# |    ./test_LEDState.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module test_LEDState
# | 
set_module_property NAME test_LEDState
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Lophilo/Test
set_module_property AUTHOR "Shyu Lee"
set_module_property DISPLAY_NAME "LED State Generator"
set_module_property TOP_LEVEL_HDL_FILE test_LEDState.v
set_module_property TOP_LEVEL_HDL_MODULE test_LEDState
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME test_LEDState
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file test_LEDState.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point MRST
# | 
add_interface MRST reset end
set_interface_property MRST associatedClock MCLK
set_interface_property MRST synchronousEdges DEASSERT

set_interface_property MRST ENABLED true

add_interface_port MRST rsi_MRST_reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point MCLK
# | 
add_interface MCLK clock end
set_interface_property MCLK clockRate 0

set_interface_property MCLK ENABLED true

add_interface_port MCLK csi_MCLK_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point LEDS
# | 
add_interface LEDS avalon_streaming start
set_interface_property LEDS associatedClock MCLK
set_interface_property LEDS associatedReset MRST
set_interface_property LEDS dataBitsPerSymbol 8
set_interface_property LEDS errorDescriptor ""
set_interface_property LEDS firstSymbolInHighOrderBits true
set_interface_property LEDS maxChannel 0
set_interface_property LEDS readyLatency 0

set_interface_property LEDS ENABLED true

add_interface_port LEDS aso_LEDS_data data Output 24
add_interface_port LEDS aso_LEDS_valid valid Output 1
# | 
# +-----------------------------------
